[package]
name = "carusbaad"
version = "0.1.0"
authors = ["Bernd Dutkowski <bernd@dutkowski.net>"]
edition = "2018"

[dependencies]
libusb="0.3.0"
webpki="0.19.1"
rustls="0.15.1"

[profile.release]
lto = true
panic = 'abort'
debug = false
debug-assertions = false

